name: ci

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Build
        run: deno run --allow-read=src --allow-write=assets/js --unstable build.ts

      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && github.repository == 'justjavac/deno_trex_game'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          exclude_assets: '.github,.vscode,src,.gitattributes,.gitignore'
          publish_dir: ./build
